name: amanahppob
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0
  get: 4.6.6
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  get_storage: ^2.1.1
  path_provider: ^2.1.3

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  color: '#f7f6f1'
  color_dark: '#272727'
  image: assets/images/logos/amanah.png
  image_dark: assets/images/logos/amanah.png
  android_12: 
    image: assets/images/logos/amanah.png
    image_dark: assets/images/logos/amanah.png
    icon_background_color: '#f7f6f1'
    icon_background_color_dark: '#272727'

flutter: 
  assets: 
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/icons/
    - assets/videos/
  uses-material-design: true

